export const LOGIN_SUCCESS = "login/success"
export const LOGIN_ERROR = "login/error"
export const LOGIN_LOADING = "login/loading"
export const SIGNUP_SUCCESS = "signup/success"
export const SIGNUP_ERROR = "signup/error"
export const SIGNUP_LOADING = "signup/loading"
export const AUTH_RESET = "auth/reset"
