import my_border from "../scripts/my_border";
import my_pixel from "../scripts/my_pixel";
import { RED, SOLID, WHEAT, WHITE } from "./typography";

export const circularCategoryData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45548090884126.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822749726.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822782494.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822815262.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822848030.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536787791902.gif",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822880798.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822913566.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "shoes",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822946334.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519822979102.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45519823011870.jpg",
    w: my_pixel(150),
    h: my_pixel(150),
    bs: "",
    border: "",
    br: 0,
    name: "",
  },
];

export const bankImageData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45103367290910.jpg",
    w: my_pixel(350),
    h: my_pixel(80),
    bs: "",
    border: my_border(1,SOLID,WHEAT),
    br: 6,
    name: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45433290981406.jpg",
    w: my_pixel(350),
    h: my_pixel(80),
    bs: "",
    border: my_border(1,SOLID,WHEAT),
    br: 6,
    name: "",
  },
];
